name: Health-Check

on:
  push:
    branches:
      - main


jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: APina03/wait_for_response@master
        with:
          url: ${{ secrets.URL_HEALTH }}
          responseCode: 200
          timeout: 2000
          interval: 500
